### ISSUE TITLE
[Help wanted] Can't delete wallet after re-clone repo

### ISSUE THREAD

**Issue by timfaner** [nervosnetwork/keypering#23]
Recently I re-clone  the repo and re-install the keypering , and then I remove the folder `$HOME/.eletrum/`. When opening the keypering the wallet which imported in old keypering version  still listed in wallet and cannot be removed. How can I delete those wallet ?

**Comment by zmcNotafraid** [comment]
@timfaner which OS are you use?And how do you run the keypering? build keypering yourself or install the release version

**Comment by timfaner** [comment]
macos 10.15.7
I found the prolem. I use a very old version.
